# Generated by Django 5.0.7 on 2024-07-16 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        ('ventas', '0003_alter_venta_pendiente_de_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='detalles_ticket',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='tienda',
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Reembolsado', 'Reembolsado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_ventas', to='ventas.venta'),
        ),
    ]
