# Generated by Django 5.0.7 on 2024-07-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_remove_pago_detalles_ticket_remove_pago_tienda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='referencia_pago',
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Reembolsado', 'Reembolsado')], default='Pendiente', max_length=50),
        ),
    ]
