# Generated by Django 5.0.7 on 2024-07-11 14:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVenta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('id_ventas', models.CharField(db_index=True, max_length=6)),
                ('created_by', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField(blank=True, editable=False)),
                ('change_timestamp', models.DateTimeField(blank=True, editable=False)),
                ('tienda', models.CharField(choices=[('Madrid', 'Madrid'), ('Barcelona', 'Barcelona'), ('Valencia', 'Valencia'), ('Videollamada', 'Videollamada')], max_length=20)),
                ('envio_entrega', models.BooleanField(default=False)),
                ('estado_entrega', models.CharField(choices=[('Por Entregar o Enviar', 'Por Entregar o Enviar'), ('Entregado o Enviado', 'Entregado o Enviado'), ('Vestido Devuelto', 'Vestido Devuelto')], max_length=50)),
                ('tipo', models.CharField(choices=[('Alquiler', 'Alquiler'), ('Venta', 'Venta')], max_length=20)),
                ('fecha_entrega', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('amount_deposito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_deposito', models.CharField(blank=True, choices=[('Pendiente de Entrega', 'Pendiente de Entrega'), ('Entregado por el Cliente', 'Entregado por el Cliente'), ('Devuelto al Cliente', 'Devuelto al Cliente')], max_length=50, null=True)),
                ('firma', models.TextField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('precio_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pendiente_de_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado_venta', models.CharField(max_length=50)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('devolucion', models.TextField(blank=True, null=True)),
                ('nombre_calendario', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.TextField(blank=True, max_length=100, null=True)),
                ('identificacion', models.TextField(blank=True, max_length=100, null=True)),
                ('identificacion_trasera', models.TextField(blank=True, max_length=100, null=True)),
                ('coste_fotos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiara', models.CharField(blank=True, choices=[('Entregada', 'Entregada'), ('No entregada', 'No entregada'), ('Sin tiara', 'Sin tiara')], max_length=50, null=True)),
                ('cancan', models.CharField(blank=True, choices=[('3 aros', '3 aros'), ('6 aros', '6 aros'), ('8 aros', '8 aros')], max_length=50, null=True)),
                ('fecha_extra_fotos', models.DateField(blank=True, null=True)),
                ('compras', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_clientes', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'historical venta',
                'verbose_name_plural': 'historical ventas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ventas', models.CharField(max_length=6, unique=True)),
                ('created_by', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('change_timestamp', models.DateTimeField(auto_now=True)),
                ('tienda', models.CharField(choices=[('Madrid', 'Madrid'), ('Barcelona', 'Barcelona'), ('Valencia', 'Valencia'), ('Videollamada', 'Videollamada')], max_length=20)),
                ('envio_entrega', models.BooleanField(default=False)),
                ('estado_entrega', models.CharField(choices=[('Por Entregar o Enviar', 'Por Entregar o Enviar'), ('Entregado o Enviado', 'Entregado o Enviado'), ('Vestido Devuelto', 'Vestido Devuelto')], max_length=50)),
                ('tipo', models.CharField(choices=[('Alquiler', 'Alquiler'), ('Venta', 'Venta')], max_length=20)),
                ('fecha_entrega', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('amount_deposito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_deposito', models.CharField(blank=True, choices=[('Pendiente de Entrega', 'Pendiente de Entrega'), ('Entregado por el Cliente', 'Entregado por el Cliente'), ('Devuelto al Cliente', 'Devuelto al Cliente')], max_length=50, null=True)),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('direccion', models.TextField(blank=True, null=True)),
                ('precio_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pendiente_de_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado_venta', models.CharField(max_length=50)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('devolucion', models.TextField(blank=True, null=True)),
                ('nombre_calendario', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('identificacion', models.ImageField(blank=True, null=True, upload_to='identificaciones/')),
                ('identificacion_trasera', models.ImageField(blank=True, null=True, upload_to='identificaciones/')),
                ('coste_fotos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiara', models.CharField(blank=True, choices=[('Entregada', 'Entregada'), ('No entregada', 'No entregada'), ('Sin tiara', 'Sin tiara')], max_length=50, null=True)),
                ('cancan', models.CharField(blank=True, choices=[('3 aros', '3 aros'), ('6 aros', '6 aros'), ('8 aros', '8 aros')], max_length=50, null=True)),
                ('fecha_extra_fotos', models.DateField(blank=True, null=True)),
                ('compras', models.TextField(blank=True, null=True)),
                ('id_clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('productos_alquiler', models.ManyToManyField(blank=True, to='productos.productoalquiler')),
                ('productos_venta', models.ManyToManyField(blank=True, to='productos.productoventa')),
            ],
        ),
    ]
