# Generated by Django 5.0.7 on 2024-07-16 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_pendiente_de_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='pendiente_de_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_pagos', to='ventas.venta')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
