# Generated by Django 5.0.7 on 2024-07-24 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('changetimestamp', models.DateTimeField(auto_now=True)),
                ('recuerdo', models.CharField(choices=[('Cojín', 'Cojín'), ('Espejos', 'Espejos'), ('Muñecas', 'Muñecas'), ('Monedero', 'Monedero'), ('Imán', 'Imán'), ('Taza', 'Taza'), ('Cuadro Foto', 'Cuadro Foto'), ('Ramo Personalizado', 'Ramo Personalizado')], max_length=50)),
                ('estado_pedido', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], max_length=50)),
                ('comentarios', models.TextField(blank=True)),
                ('tienda', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateField()),
                ('nombre_imprimir', models.CharField(max_length=100)),
                ('fecha_imprimir', models.DateField()),
                ('color', models.CharField(choices=[('Rosa', 'Rosa'), ('Morado', 'Morado'), ('Rojo', 'Rojo'), ('Rojo Vino', 'Rojo Vino'), ('Verde Claro', 'Verde Claro'), ('Verde Oscuro', 'Verde Oscuro'), ('Turquesa', 'Turquesa'), ('Azul Oscuro', 'Azul Oscuro'), ('Azul Claro', 'Azul Claro'), ('Amarillo', 'Amarillo'), ('Negro', 'Negro')], max_length=50)),
                ('numero_unidades', models.IntegerField(default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name_plural': 'PedidoProductos',
            },
        ),
    ]
