# Generated by Django 5.0.7 on 2024-07-11 14:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Vestido', 'Vestido'), ('Accesorios', 'Accesorios'), ('Complementos', 'Complementos'), ('Otros', 'Otros')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=50)),
                ('precio_alquiler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='productos/alquiler/')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja')], max_length=50)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Vestido', 'Vestido'), ('Accesorios', 'Accesorios'), ('Complementos', 'Complementos'), ('Otros', 'Otros')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=50)),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='productos/venta/')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja')], max_length=50)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalProductoAlquiler',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('id_producto', models.CharField(db_index=True, max_length=6)),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Vestido', 'Vestido'), ('Accesorios', 'Accesorios'), ('Complementos', 'Complementos'), ('Otros', 'Otros')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=50)),
                ('precio_alquiler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja')], max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical producto alquiler',
                'verbose_name_plural': 'historical producto alquilers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductoVenta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('id_producto', models.CharField(db_index=True, max_length=6)),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Vestido', 'Vestido'), ('Accesorios', 'Accesorios'), ('Complementos', 'Complementos'), ('Otros', 'Otros')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=50)),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja')], max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical producto venta',
                'verbose_name_plural': 'historical producto ventas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ReservaAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productoalquiler')),
            ],
        ),
    ]
