# Generated by Django 5.0.7 on 2024-07-16 15:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('label_precio', models.CharField(blank=True, max_length=255)),
                ('almacen_m', models.IntegerField(default=0)),
                ('madrid', models.IntegerField(default=0)),
                ('barcelona', models.IntegerField(default=0)),
                ('tienda', models.CharField(choices=[('Madrid', 'Madrid'), ('Barcelona', 'Barcelona'), ('Valencia', 'Valencia'), ('Videollamada', 'Videollamada')], max_length=50)),
                ('categoria', models.CharField(choices=[('Vestido', 'Vestido'), ('Vestido Corto', 'Vestido Corto'), ('Accesorios', 'Accesorios'), ('Complementos', 'Complementos'), ('Envio', 'Envio'), ('Invitaciones', 'Invitaciones'), ('Paquete Fotos', 'Paquete Fotos'), ('Recuerdos', 'Recuerdos'), ('Otros', 'Otros')], max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=10)),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja')], max_length=10)),
                ('tipo', models.CharField(choices=[('Venta', 'Venta'), ('Alquiler', 'Alquiler')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
