# Generated by Django 5.0.7 on 2024-07-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='almacen_m',
            new_name='valencia',
        ),
        migrations.AlterField(
            model_name='producto',
            name='label_precio',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
