# Generated by Django 5.0.7 on 2024-07-26 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoalquiler',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_alquiler', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productoalquiler'),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_venta', to='ventas.venta'),
        ),
    ]
