# Generated by Django 5.0.7 on 2024-07-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_cliente',
            field=models.CharField(choices=[('En Proceso de compra', 'En Proceso de compra'), ('ya compró', 'Ya Compró'), ('perdido', 'Perdido')], max_length=50),
        ),
    ]
