# Generated by Django 5.0.7 on 2024-07-26 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionFoto',
            fields=[
                ('id_sesion', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('changetimestamp', models.DateTimeField(auto_now=True)),
                ('fecha_sesion', models.DateField()),
                ('duracion', models.DurationField()),
                ('lugar', models.CharField(max_length=100)),
                ('estado_sesion', models.CharField(choices=[('Pendiente de confirmar', 'Pendiente de confirmar'), ('Confirmada', 'Confirmada'), ('En Edición', 'En Edición'), ('Pendiente Link', 'Pendiente Link'), ('Link Enviado', 'Link Enviado'), ('Pendiente Nº Fotos', 'Pendiente Nº Fotos'), ('Pendiente Albúm', 'Pendiente Albúm'), ('En Espera de Recibir Albúm', 'En Espera de Recibir Albúm'), ('Completada', 'Completada'), ('Reedición', 'Reedición'), ('Cancelada', 'Cancelada')], max_length=50)),
                ('extras', models.TextField(blank=True)),
                ('fecha_segunda_sesion', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productoventa')),
            ],
            options={
                'verbose_name_plural': 'Sesiones de Fotos',
            },
        ),
    ]
