# Generated by Django 5.0.7 on 2024-07-24 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones_fotos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionfoto',
            name='venta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sesionfoto',
            name='estado_sesion',
            field=models.CharField(choices=[('Pendiente de confirmar', 'Pendiente de confirmar'), ('Confirmada', 'Confirmada'), ('En Edición', 'En Edición'), ('Pendiente Link', 'Pendiente Link'), ('Link Enviado', 'Link Enviado'), ('Pendiente Nº Fotos', 'Pendiente Nº Fotos'), ('Pendiente Albúm', 'Pendiente Albúm'), ('En Espera de Recibir Albúm', 'En Espera de Recibir Albúm'), ('Completada', 'Completada'), ('Reedición', 'Reedición'), ('Cancelada', 'Cancelada')], max_length=50),
        ),
    ]
