# Generated by Django 5.0.7 on 2024-07-24 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones_fotos', '0002_sesionfoto_venta_alter_sesionfoto_estado_sesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesionfoto',
            name='precio',
        ),
    ]
