# Generated by Django 5.0.7 on 2024-07-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones_fotos', '0004_sesionfoto_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesionfoto',
            name='precio_unitario',
        ),
    ]
