# Generated by Django 5.0.7 on 2024-07-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones_fotos', '0005_remove_sesionfoto_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionfoto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
